modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="new_borders_mod"
version="1.0.0"
displayName="New Borders Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Lima, ZitsyZits"

[[dependencies.new_borders_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




